[programs.localnet]
multi_airdrop = "6xi2VWSkxXcxoXm8snHunB3CyWfxLKrUPm3nC4EXRtk9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/workspace/new-pair.json"

[scripts]
test = "mocha -t 1000000 ./tests/"
